/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1238Collection } from "./ERC1238Collection";
export type { ERC1238URIStorage } from "./ERC1238URIStorage";
export type { IERC1238Collection } from "./IERC1238Collection";
export type { IERC1238URIStorage } from "./IERC1238URIStorage";
