/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace IMerkleTreeNode {
  export type BatchAddNodeStruct = {
    hash: PromiseOrValue<BytesLike>;
    groupName: PromiseOrValue<BytesLike>;
    groupId: PromiseOrValue<BytesLike>;
    index: PromiseOrValue<BigNumberish>;
    level: PromiseOrValue<BigNumberish>;
  };

  export type BatchAddNodeStructOutput = [
    string,
    string,
    string,
    BigNumber,
    BigNumber
  ] & {
    hash: string;
    groupName: string;
    groupId: string;
    index: BigNumber;
    level: BigNumber;
  };

  export type BatchUpdateNodeStruct = {
    hash: PromiseOrValue<BytesLike>;
    groupId: PromiseOrValue<BytesLike>;
    index: PromiseOrValue<BigNumberish>;
    level: PromiseOrValue<BigNumberish>;
  };

  export type BatchUpdateNodeStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber
  ] & { hash: string; groupId: string; index: BigNumber; level: BigNumber };

  export type BatchUpdateNodeProStruct = {
    siblingHash: PromiseOrValue<BytesLike>;
    groupId: PromiseOrValue<BytesLike>;
    parentIndex: PromiseOrValue<BigNumberish>;
    parentLevel: PromiseOrValue<BigNumberish>;
  };

  export type BatchUpdateNodeProStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber
  ] & {
    siblingHash: string;
    groupId: string;
    parentIndex: BigNumber;
    parentLevel: BigNumber;
  };

  export type ParentLocateStruct = {
    groupId: PromiseOrValue<BytesLike>;
    index: PromiseOrValue<BigNumberish>;
    level: PromiseOrValue<BigNumberish>;
  };

  export type ParentLocateStructOutput = [string, BigNumber, BigNumber] & {
    groupId: string;
    index: BigNumber;
    level: BigNumber;
  };

  export type MerkleTreeNodeStruct = {
    hash: PromiseOrValue<BytesLike>;
    groupName: PromiseOrValue<BytesLike>;
    siblingHash: PromiseOrValue<BytesLike>;
    groupId: PromiseOrValue<BytesLike>;
    index: PromiseOrValue<BigNumberish>;
    level: PromiseOrValue<BigNumberish>;
    parent: IMerkleTreeNode.ParentLocateStruct;
  };

  export type MerkleTreeNodeStructOutput = [
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    IMerkleTreeNode.ParentLocateStructOutput
  ] & {
    hash: string;
    groupName: string;
    siblingHash: string;
    groupId: string;
    index: BigNumber;
    level: BigNumber;
    parent: IMerkleTreeNode.ParentLocateStructOutput;
  };
}

export interface MerkleTreeInterface extends utils.Interface {
  functions: {
    "batchAddNode(address,(bytes32,bytes32,bytes16,uint64,uint64)[])": FunctionFragment;
    "batchUpdateNode(address,(bytes32,bytes16,uint64,uint64)[])": FunctionFragment;
    "batchUpdateNodePro(address,(bytes32,bytes16,uint64,uint64)[])": FunctionFragment;
    "getAllNodes(bytes16)": FunctionFragment;
    "getNode(bytes16,uint256,uint256)": FunctionFragment;
    "getNodeByHash(bytes16,bytes32)": FunctionFragment;
    "getNodeCounts(bytes16)": FunctionFragment;
    "getSameLevelNodesLength(bytes16,uint256)": FunctionFragment;
    "merkleTrees(uint256)": FunctionFragment;
    "nums()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "batchAddNode"
      | "batchUpdateNode"
      | "batchUpdateNodePro"
      | "getAllNodes"
      | "getNode"
      | "getNodeByHash"
      | "getNodeCounts"
      | "getSameLevelNodesLength"
      | "merkleTrees"
      | "nums"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "batchAddNode",
    values: [PromiseOrValue<string>, IMerkleTreeNode.BatchAddNodeStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchUpdateNode",
    values: [PromiseOrValue<string>, IMerkleTreeNode.BatchUpdateNodeStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchUpdateNodePro",
    values: [PromiseOrValue<string>, IMerkleTreeNode.BatchUpdateNodeProStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllNodes",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getNode",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeByHash",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeCounts",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getSameLevelNodesLength",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "merkleTrees",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "nums", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "batchAddNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchUpdateNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchUpdateNodePro",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllNodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getNodeByHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSameLevelNodesLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "merkleTrees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nums", data: BytesLike): Result;

  events: {};
}

export interface MerkleTree extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MerkleTreeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    batchAddNode(
      _signer: PromiseOrValue<string>,
      txs: IMerkleTreeNode.BatchAddNodeStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    batchUpdateNode(
      _signer: PromiseOrValue<string>,
      txs: IMerkleTreeNode.BatchUpdateNodeStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    batchUpdateNodePro(
      _signer: PromiseOrValue<string>,
      txs: IMerkleTreeNode.BatchUpdateNodeProStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAllNodes(
      _groupId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [IMerkleTreeNode.MerkleTreeNodeStructOutput[]] & {
        allNodes: IMerkleTreeNode.MerkleTreeNodeStructOutput[];
      }
    >;

    getNode(
      _groupId: PromiseOrValue<BytesLike>,
      _level: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [IMerkleTreeNode.MerkleTreeNodeStructOutput] & {
        node: IMerkleTreeNode.MerkleTreeNodeStructOutput;
      }
    >;

    getNodeByHash(
      _groupId: PromiseOrValue<BytesLike>,
      _hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [IMerkleTreeNode.MerkleTreeNodeStructOutput] & {
        node: IMerkleTreeNode.MerkleTreeNodeStructOutput;
      }
    >;

    getNodeCounts(
      _groupId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { nodeCounts: BigNumber }>;

    getSameLevelNodesLength(
      _groupId: PromiseOrValue<BytesLike>,
      _level: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { counts: BigNumber }>;

    merkleTrees(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string] & { groupId: string }>;

    nums(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  batchAddNode(
    _signer: PromiseOrValue<string>,
    txs: IMerkleTreeNode.BatchAddNodeStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  batchUpdateNode(
    _signer: PromiseOrValue<string>,
    txs: IMerkleTreeNode.BatchUpdateNodeStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  batchUpdateNodePro(
    _signer: PromiseOrValue<string>,
    txs: IMerkleTreeNode.BatchUpdateNodeProStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAllNodes(
    _groupId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<IMerkleTreeNode.MerkleTreeNodeStructOutput[]>;

  getNode(
    _groupId: PromiseOrValue<BytesLike>,
    _level: PromiseOrValue<BigNumberish>,
    _index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<IMerkleTreeNode.MerkleTreeNodeStructOutput>;

  getNodeByHash(
    _groupId: PromiseOrValue<BytesLike>,
    _hash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<IMerkleTreeNode.MerkleTreeNodeStructOutput>;

  getNodeCounts(
    _groupId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getSameLevelNodesLength(
    _groupId: PromiseOrValue<BytesLike>,
    _level: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  merkleTrees(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  nums(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    batchAddNode(
      _signer: PromiseOrValue<string>,
      txs: IMerkleTreeNode.BatchAddNodeStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    batchUpdateNode(
      _signer: PromiseOrValue<string>,
      txs: IMerkleTreeNode.BatchUpdateNodeStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    batchUpdateNodePro(
      _signer: PromiseOrValue<string>,
      txs: IMerkleTreeNode.BatchUpdateNodeProStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    getAllNodes(
      _groupId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<IMerkleTreeNode.MerkleTreeNodeStructOutput[]>;

    getNode(
      _groupId: PromiseOrValue<BytesLike>,
      _level: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<IMerkleTreeNode.MerkleTreeNodeStructOutput>;

    getNodeByHash(
      _groupId: PromiseOrValue<BytesLike>,
      _hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<IMerkleTreeNode.MerkleTreeNodeStructOutput>;

    getNodeCounts(
      _groupId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSameLevelNodesLength(
      _groupId: PromiseOrValue<BytesLike>,
      _level: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    merkleTrees(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    nums(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    batchAddNode(
      _signer: PromiseOrValue<string>,
      txs: IMerkleTreeNode.BatchAddNodeStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    batchUpdateNode(
      _signer: PromiseOrValue<string>,
      txs: IMerkleTreeNode.BatchUpdateNodeStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    batchUpdateNodePro(
      _signer: PromiseOrValue<string>,
      txs: IMerkleTreeNode.BatchUpdateNodeProStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAllNodes(
      _groupId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNode(
      _groupId: PromiseOrValue<BytesLike>,
      _level: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNodeByHash(
      _groupId: PromiseOrValue<BytesLike>,
      _hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNodeCounts(
      _groupId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSameLevelNodesLength(
      _groupId: PromiseOrValue<BytesLike>,
      _level: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    merkleTrees(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nums(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    batchAddNode(
      _signer: PromiseOrValue<string>,
      txs: IMerkleTreeNode.BatchAddNodeStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    batchUpdateNode(
      _signer: PromiseOrValue<string>,
      txs: IMerkleTreeNode.BatchUpdateNodeStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    batchUpdateNodePro(
      _signer: PromiseOrValue<string>,
      txs: IMerkleTreeNode.BatchUpdateNodeProStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAllNodes(
      _groupId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNode(
      _groupId: PromiseOrValue<BytesLike>,
      _level: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNodeByHash(
      _groupId: PromiseOrValue<BytesLike>,
      _hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNodeCounts(
      _groupId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSameLevelNodesLength(
      _groupId: PromiseOrValue<BytesLike>,
      _level: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    merkleTrees(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nums(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
