/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1238Collection__factory } from "./ERC1238Collection__factory";
export { ERC1238URIStorage__factory } from "./ERC1238URIStorage__factory";
export { IERC1238Collection__factory } from "./IERC1238Collection__factory";
export { IERC1238URIStorage__factory } from "./IERC1238URIStorage__factory";
