/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extensions from "./extensions";
export type { extensions };
export type { ERC1238 } from "./ERC1238";
export type { ERC1238Approval } from "./ERC1238Approval";
export type { IERC1238 } from "./IERC1238";
export type { IERC1238Receiver } from "./IERC1238Receiver";
