/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IYoMinter,
  IYoMinterInterface,
} from "../../../contracts/interface/IYoMinter";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "Minted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "signal",
        type: "bytes32",
      },
    ],
    name: "ProofVerified",
    type: "event",
  },
];

export class IYoMinter__factory {
  static readonly abi = _abi;
  static createInterface(): IYoMinterInterface {
    return new utils.Interface(_abi) as IYoMinterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IYoMinter {
    return new Contract(address, _abi, signerOrProvider) as IYoMinter;
  }
}
