/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace ICommitment {
  export type CommitmentStruct = {
    id: PromiseOrValue<BigNumberish>;
    userId: PromiseOrValue<string>;
    groupId: PromiseOrValue<BigNumberish>;
    data: PromiseOrValue<BytesLike>;
    metadata: PromiseOrValue<string>;
    mintAddress: PromiseOrValue<string>;
    createdAt: PromiseOrValue<BigNumberish>;
  };

  export type CommitmentStructOutput = [
    BigNumber,
    string,
    BigNumber,
    string,
    string,
    string,
    BigNumber
  ] & {
    id: BigNumber;
    userId: string;
    groupId: BigNumber;
    data: string;
    metadata: string;
    mintAddress: string;
    createdAt: BigNumber;
  };
}

export interface CommitmentInterface extends utils.Interface {
  functions: {
    "addCom(address,uint256,bytes32,uint256,string,uint256)": FunctionFragment;
    "getAllComs(address)": FunctionFragment;
    "getComsLength(address)": FunctionFragment;
    "updateCom(string,address,address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addCom"
      | "getAllComs"
      | "getComsLength"
      | "updateCom"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addCom",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllComs",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getComsLength",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCom",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "addCom", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAllComs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getComsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateCom", data: BytesLike): Result;

  events: {};
}

export interface Commitment extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CommitmentInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addCom(
      _address: PromiseOrValue<string>,
      _id: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      _groupId: PromiseOrValue<BigNumberish>,
      _userId: PromiseOrValue<string>,
      _createdAt: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAllComs(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [ICommitment.CommitmentStructOutput[]] & {
        commitments: ICommitment.CommitmentStructOutput[];
      }
    >;

    getComsLength(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { length: BigNumber }>;

    updateCom(
      _metadta: PromiseOrValue<string>,
      _mintAddress: PromiseOrValue<string>,
      _address: PromiseOrValue<string>,
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  addCom(
    _address: PromiseOrValue<string>,
    _id: PromiseOrValue<BigNumberish>,
    _data: PromiseOrValue<BytesLike>,
    _groupId: PromiseOrValue<BigNumberish>,
    _userId: PromiseOrValue<string>,
    _createdAt: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAllComs(
    _address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ICommitment.CommitmentStructOutput[]>;

  getComsLength(
    _address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  updateCom(
    _metadta: PromiseOrValue<string>,
    _mintAddress: PromiseOrValue<string>,
    _address: PromiseOrValue<string>,
    _id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    addCom(
      _address: PromiseOrValue<string>,
      _id: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      _groupId: PromiseOrValue<BigNumberish>,
      _userId: PromiseOrValue<string>,
      _createdAt: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getAllComs(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ICommitment.CommitmentStructOutput[]>;

    getComsLength(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateCom(
      _metadta: PromiseOrValue<string>,
      _mintAddress: PromiseOrValue<string>,
      _address: PromiseOrValue<string>,
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    addCom(
      _address: PromiseOrValue<string>,
      _id: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      _groupId: PromiseOrValue<BigNumberish>,
      _userId: PromiseOrValue<string>,
      _createdAt: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAllComs(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getComsLength(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateCom(
      _metadta: PromiseOrValue<string>,
      _mintAddress: PromiseOrValue<string>,
      _address: PromiseOrValue<string>,
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addCom(
      _address: PromiseOrValue<string>,
      _id: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      _groupId: PromiseOrValue<BigNumberish>,
      _userId: PromiseOrValue<string>,
      _createdAt: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAllComs(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getComsLength(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateCom(
      _metadta: PromiseOrValue<string>,
      _mintAddress: PromiseOrValue<string>,
      _address: PromiseOrValue<string>,
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
