/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace IMerkleTreeNode {
  export type ParentLocateStruct = {
    groupId: PromiseOrValue<BigNumberish>;
    index: PromiseOrValue<BigNumberish>;
    level: PromiseOrValue<BigNumberish>;
  };

  export type ParentLocateStructOutput = [BigNumber, BigNumber, BigNumber] & {
    groupId: BigNumber;
    index: BigNumber;
    level: BigNumber;
  };

  export type MerkleTreeNodeStruct = {
    id: PromiseOrValue<BigNumberish>;
    data: PromiseOrValue<BytesLike>;
    groupId: PromiseOrValue<BigNumberish>;
    groupName: PromiseOrValue<string>;
    index: PromiseOrValue<BigNumberish>;
    level: PromiseOrValue<BigNumberish>;
    siblingHash: PromiseOrValue<BytesLike>;
    parent: IMerkleTreeNode.ParentLocateStruct;
  };

  export type MerkleTreeNodeStructOutput = [
    BigNumber,
    string,
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    string,
    IMerkleTreeNode.ParentLocateStructOutput
  ] & {
    id: BigNumber;
    data: string;
    groupId: BigNumber;
    groupName: string;
    index: BigNumber;
    level: BigNumber;
    siblingHash: string;
    parent: IMerkleTreeNode.ParentLocateStructOutput;
  };
}

export interface MerkleTreeInterface extends utils.Interface {
  functions: {
    "addNode(bytes32,uint256,string,uint256,uint256)": FunctionFragment;
    "getAllNodes(uint256)": FunctionFragment;
    "getNode(uint256,uint256,uint256)": FunctionFragment;
    "getNodeByHash(uint256,bytes32)": FunctionFragment;
    "getNodeCounts(uint256)": FunctionFragment;
    "merkleTrees(uint256)": FunctionFragment;
    "nums()": FunctionFragment;
    "updateNode(uint256,uint256,uint256,bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addNode"
      | "getAllNodes"
      | "getNode"
      | "getNodeByHash"
      | "getNodeCounts"
      | "merkleTrees"
      | "nums"
      | "updateNode"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addNode",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllNodes",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getNode",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeByHash",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeCounts",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "merkleTrees",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "nums", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateNode",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "addNode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllNodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getNodeByHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "merkleTrees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nums", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateNode", data: BytesLike): Result;

  events: {};
}

export interface MerkleTree extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MerkleTreeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addNode(
      _data: PromiseOrValue<BytesLike>,
      _groupId: PromiseOrValue<BigNumberish>,
      _groupName: PromiseOrValue<string>,
      _level: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAllNodes(
      _groupId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [IMerkleTreeNode.MerkleTreeNodeStructOutput[]] & {
        allNodes: IMerkleTreeNode.MerkleTreeNodeStructOutput[];
      }
    >;

    getNode(
      _groupId: PromiseOrValue<BigNumberish>,
      _level: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [IMerkleTreeNode.MerkleTreeNodeStructOutput] & {
        node: IMerkleTreeNode.MerkleTreeNodeStructOutput;
      }
    >;

    getNodeByHash(
      _groupId: PromiseOrValue<BigNumberish>,
      _hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [IMerkleTreeNode.MerkleTreeNodeStructOutput] & {
        node: IMerkleTreeNode.MerkleTreeNodeStructOutput;
      }
    >;

    getNodeCounts(
      _groupId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { nodeCounts: BigNumber }>;

    merkleTrees(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { groupId: BigNumber }>;

    nums(overrides?: CallOverrides): Promise<[BigNumber]>;

    updateNode(
      _groupId: PromiseOrValue<BigNumberish>,
      _level: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  addNode(
    _data: PromiseOrValue<BytesLike>,
    _groupId: PromiseOrValue<BigNumberish>,
    _groupName: PromiseOrValue<string>,
    _level: PromiseOrValue<BigNumberish>,
    _index: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAllNodes(
    _groupId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<IMerkleTreeNode.MerkleTreeNodeStructOutput[]>;

  getNode(
    _groupId: PromiseOrValue<BigNumberish>,
    _level: PromiseOrValue<BigNumberish>,
    _index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<IMerkleTreeNode.MerkleTreeNodeStructOutput>;

  getNodeByHash(
    _groupId: PromiseOrValue<BigNumberish>,
    _hash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<IMerkleTreeNode.MerkleTreeNodeStructOutput>;

  getNodeCounts(
    _groupId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  merkleTrees(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  nums(overrides?: CallOverrides): Promise<BigNumber>;

  updateNode(
    _groupId: PromiseOrValue<BigNumberish>,
    _level: PromiseOrValue<BigNumberish>,
    _index: PromiseOrValue<BigNumberish>,
    _data: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    addNode(
      _data: PromiseOrValue<BytesLike>,
      _groupId: PromiseOrValue<BigNumberish>,
      _groupName: PromiseOrValue<string>,
      _level: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getAllNodes(
      _groupId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<IMerkleTreeNode.MerkleTreeNodeStructOutput[]>;

    getNode(
      _groupId: PromiseOrValue<BigNumberish>,
      _level: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<IMerkleTreeNode.MerkleTreeNodeStructOutput>;

    getNodeByHash(
      _groupId: PromiseOrValue<BigNumberish>,
      _hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<IMerkleTreeNode.MerkleTreeNodeStructOutput>;

    getNodeCounts(
      _groupId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    merkleTrees(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nums(overrides?: CallOverrides): Promise<BigNumber>;

    updateNode(
      _groupId: PromiseOrValue<BigNumberish>,
      _level: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    addNode(
      _data: PromiseOrValue<BytesLike>,
      _groupId: PromiseOrValue<BigNumberish>,
      _groupName: PromiseOrValue<string>,
      _level: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAllNodes(
      _groupId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNode(
      _groupId: PromiseOrValue<BigNumberish>,
      _level: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNodeByHash(
      _groupId: PromiseOrValue<BigNumberish>,
      _hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNodeCounts(
      _groupId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    merkleTrees(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nums(overrides?: CallOverrides): Promise<BigNumber>;

    updateNode(
      _groupId: PromiseOrValue<BigNumberish>,
      _level: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addNode(
      _data: PromiseOrValue<BytesLike>,
      _groupId: PromiseOrValue<BigNumberish>,
      _groupName: PromiseOrValue<string>,
      _level: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAllNodes(
      _groupId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNode(
      _groupId: PromiseOrValue<BigNumberish>,
      _level: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNodeByHash(
      _groupId: PromiseOrValue<BigNumberish>,
      _hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNodeCounts(
      _groupId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    merkleTrees(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nums(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateNode(
      _groupId: PromiseOrValue<BigNumberish>,
      _level: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
